### ISSUE TITLE
Fill in the stub - break this ticket into n tickets.

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/camera_model#11]
DoD: n Tickets to determine implementation requirements / order.

**Comment by ihumphrey-usgs** [comment]
# MdisPlugin

does csm have standard for documentation? id doc even necessary since trd has doc?

- [ ] #13 - keywords must be determined, implement members.

- [ ]Implement and document the accessors for model metadata:

- [ ] implement ISD construction methods
  1. canModelBeConstructedFromISD()
  2. constructModelFromISD()

- [ ] implement state construction methods
  1. canModelBeConstructedFromState()
  2. constructModelFromState()
  3. getModelNameFromModelState()

- [ ] implement ISD conversion methods
  1. canISDBeConvertedToModelState()
  2. convertISDToModelState()
