### ISSUE TITLE
(2) Write a CL tool that allows you to generate MDIS ISD.

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/camera_model#48]

**Comment by jlaura** [comment]
From our meeting today, this ISD is going to be in JSON format.  Does C++ have native JSON support or do you all use a JSON library?

**Comment by twilson271828** [comment]
I'm moving this to resolved.  Was going to try and implement JSON functionality before I left, but that's a separate ticket.  I do not believe C++ has native JSON support, and have not looked at 3rd party libraries.  
Since the structure of the file is very simple (keyword-value pairs), I was thinking about not using a 3rd party library because of the added dependency issues that arise.  Most of the bugs currently in ISIS were introduced through third-party libraries.
