### ISSUE TITLE
(4) Implement the distortion model in imageToground

### ISSUE THREAD

**Issue by jlaura** [USGS-Astrogeology/camera_model#64]
DoD: 

* Camera Implements Distortion Model

**Comment by ihumphrey-usgs** [comment]
[MDIS IK - MDIS Distortion Model](http://naif.jpl.nasa.gov/pub/naif/pds/data/mess-e_v_h-spice-6-v1.0/messsp_1000/data/ik/msgr_mdis_v160.ti)

When looking at the IK for MDIS NAC, it looks like the distortion model described is being used in the instrument coordinates to image pixel coordinates conversion. Is this applicable in imageToGround or groundToImage?

**Comment by thareUSGS** [comment]
This is a good topic to remember to ask Ken.  I have read in two locations this is up to us and can be implemented in initial image calibration or within the CSM.
(2) http://www.gwg.nga.mil/documents/csmwg/documents/Frame_Formulation_Paper_Version_2.1_July2011.pdf
--On the second paper see page 19 (page 23 in the PDF).
(2) http://www.sensorml.com/sensorML-2.0/examples/csmFrame.html (top of the page).

**Comment by thareUSGS** [comment]
Just for more information on the topic. For commercial data, images are nearly always calibrated in-house, prior to releasing in the wild, such that more generic sensor models can use them. This is how companies protect their proprietary instruments but allow others to process them. 

Generally this is where you will see Rational Polynomial Coefficients (RPCs) or the newer Replacement Sensor Models (RSMs) . Quote: _"RPCs provide a compact representation of a ground-to-image geometry, allowing photogrammetric processing without requiring a physical camera model."_ So RPCs or RSMs could be be considered almost one step beyond a camera sensor model since a camera model is no longer needed.

We may need to live somewhere **in the middle** providing calibrated images but with fully functional CSMs so our users are not stuck with potential RPC or RSM limitations. This something that may be decided per instrument but ideally we should settle on a standard procedure here - yet to be determined.

**Comment by jlaura** [comment]
/work/projects/IAA_camera/data/*.ti - this file has the distortion model parameters.
